<%@ Page Title="Upravljanje z knjigami" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="KnjigeNaVoljo.aspx.cs" Inherits="KnjigeNaVoljo" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <!DOCTYPE html>

    <html>
    <head>
        <title>Upravljanje z knjigami</title>

        <webopt:BundleReference runat="server" Path="~/Content/css" />

        <link rel="stylesheet" type="text/css" href="stili.css" />
        <style type="text/css">
            .auto-style4 {
                width: 829px;
            }

            .auto-style5 {
                width: 41px;
            }

            .auto-style6 {
                width: 750px;
            }

            .auto-style7 {
                height: 546px;
                width: 1170px;
                text-align: center;
                margin-left: auto;
                margin-right: auto;
                margin-top: 0px;
                padding-left: 15px;
                padding-right: 15px;
            }
        </style>
    </head>
    <body>

        <asp:Label ID="Message"
            ForeColor="Red"
            runat="server" />
        <h1>Upravljanje z knjigami</h1>
        <hr style="width: 100%;" />

        <%-- GridView Knjig ki so trenutno na voljo --%>
        <div class="row">
            <div class="col-md-8" style="text-align: center; width: 800px; margin: 10px auto;" draggable="true">
                <h3 style="text-align: left; font-weight: 700">Knjige na voljo</h3>
                <br>
                <div class="row">
                    <div style="text-align: center; margin: 10px auto; width: 815px; height: 400px; overflow-y: auto; overflow-x: hidden;" draggable="true">
                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ID" DataSourceID="Knjige" Height="230px" Width="800px" CssClass="auto-style1" HorizontalAlign="Justify"
                            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" PageSize="25" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Horizontal" AllowSorting="True">
                            <FooterStyle BackColor="#CCCCCC" />
                            <HeaderStyle Height="35px" HorizontalAlign="Center" BackColor="Black" Font-Bold="True" ForeColor="White" />
                            <PagerSettings FirstPageText="&amp;lt; &amp;lt;" />
                            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                            <RowStyle Height="25px" HorizontalAlign="Center" VerticalAlign="NotSet" />
                            <AlternatingRowStyle BackColor="#CCCCCC" />
                            <Columns>
                                <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                                <asp:BoundField DataField="NaslovKnjige" HeaderText="Naslov knjige" SortExpression="NaslovKnjige" />
                                <asp:BoundField DataField="Pisatelj" HeaderText="Pisatelj" SortExpression="Pisatelj" />
                                <asp:BoundField DataField="LetoIzdaje" HeaderText="Leto izdaje" SortExpression="LetoIzdaje" />
                                <asp:BoundField DataField="NaVoljo" HeaderText="Zaloga" SortExpression="NaVoljo" />
                            </Columns>
                            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="Gray" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#383838" />
                        </asp:GridView>
                        <asp:SqlDataSource ID="Knjige" runat="server" ConnectionString="<%$ ConnectionStrings:myConnectionString %>"
                            SelectCommand="SELECT * FROM [Knjige]"
                            DeleteCommand="DELETE FROM Knjige WHERE ID = @ID"
                            UpdateCommand="UPDATE Knjige SET NaslovKnjige=@NaslovKnjige, Pisatelj=@Pisatelj, LetoIzdaje=@LetoIzdaje, NaVoljo=@NaVoljo WHERE ID=@ID"></asp:SqlDataSource>
                        <br />
                    </div>
                </div>
            </div>



            <%--DODAJANJE KNJIGE--%>
            <div class="col-md-4" style="margin: 75px auto;">
                <h3 style="text-align: left; font-weight: 700">Dodaj knjigo</h3>
                <hr />
                <table border="0" style="width: 300px; font-size: large;">
                    <tr>
                        <td>Naslov knjige:</td>
                        <td>
                            <asp:TextBox ID="naslovKnjige" runat="server" Width="140" />
                        </td>
                    </tr>
                    <tr>
                        <td>Pisatelj:</td>
                        <td>
                            <asp:TextBox ID="pisatelj" runat="server" Width="140" />
                        </td>
                    </tr>
                    <tr>
                        <td>Leto izdaje:</td>
                        <td>
                            <asp:TextBox ID="letoIzdaje" runat="server" Width="140" />
                        </td>
                    </tr>
                    <tr>
                        <td>Na voljo:</td>
                        <td>
                            <asp:TextBox ID="naVoljo" runat="server" Width="140" />

                        </td>
                    </tr>
                </table>
                <div style="margin-top: 20px;">
                    <asp:Button ID="btnAdd" runat="server" Text="Dodaj" OnClick="GridView1_Add" />
                </div>
            </div>
        </div>
    </body>
    </html>
</asp:Content>

